name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief explanation of the feature you’d like to see.
      placeholder: A concise summary of the feature request.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide more detailed information, context, and possible solution.
      placeholder: Describe the feature with as much detail as possible.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative or similar solutions that could resolve the issue.
    validations:
      required: false
